# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮件地址')),
                ('author_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('content', models.TextField(verbose_name='正文')),
                ('published_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
            options={
                'ordering': ['-published_time'],
                'verbose_name_plural': '留言',
            },
        ),
    ]
