# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 10:21
from __future__ import unicode_literals

from django.db import migrations
import draceditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0006_auto_20170409_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aritcle',
            name='body',
            field=draceditor.models.DraceditorField(help_text='请编写你的文章', verbose_name='正文'),
        ),
    ]
