# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0008_auto_20170411_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='分类名'),
        ),
    ]
