# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0009_auto_20170411_2304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aritcle',
            new_name='Article',
        ),
    ]
